# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('noir', 'Noir'), ('blanc', 'Blanc'), ('rouge', 'Rouge'), ('bleu', 'Bleu')], default='noir', max_length=10)),
                ('shoe_type', models.CharField(choices=[('course', 'Course'), ('marche', 'Marche'), ('ville', 'ville')], default='ville', max_length=10)),
            ],
        ),
    ]
