# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-08 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersummary',
            name='remain',
            field=models.FloatField(default=0),
        ),
    ]
