# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cardinality',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MYPRINT_ALLOWANCE', 'Allocation semestrielle'), ('FACULTY_ALLOWANCE', 'Rallonge facultaire'), ('ACCOUNT_CHARGING', "Chargement par l'étudiant"), ('PRINT_JOB', "Travail d'impression"), ('REFUND', "Remboursement sur travail d'impression")], db_index=True, max_length=100),
        ),
    ]
