# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cardinality',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
