# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0002_semestersummary_facturation_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersummary',
            name='facturation_faculty',
            field=models.TextField(default=''),
        ),
    ]
