# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0002_auto_20170503_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='acronym',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
