# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0002_semestersummary_facturation_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestersummary',
            name='facturation_faculty',
        ),
        migrations.AddField(
            model_name='semestersummary',
            name='billing_faculty',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(b'MYPRINT_ALLOWANCE', b'Allocation semestrielle'), (b'FACULTY_ALLOWANCE', b'Rallonge facultaire'), (b'ACCOUNT_CHARGING', b"Chargement par l'\xc3\xa9tudiant"), (b'PRINT_JOB', b"Travail d'impression"), (b'REFUND', b"Remboursement sur travail d'impression")], max_length=100),
        ),
        migrations.AlterField(
            model_name='updatestatus',
            name='status',
            field=models.CharField(choices=[(b'SUCCESS', b'Consolidation termin\xc3\xa9e avec succ\xc3\xa8s'), (b'FAILURE', b'Erreur durant la consolidation')], max_length=100),
        ),
    ]
