# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0002_auto_20170508_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.FloatField(default=0)),
                ('total_charged', models.FloatField(default=0)),
                ('myprint_allowance', models.FloatField(default=0)),
                ('faculty_allowance', models.FloatField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill2myprint.Section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill2myprint.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill2myprint.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='budgetsemester',
            name='section',
        ),
        migrations.RemoveField(
            model_name='budgetsemester',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='budgetsemester',
            name='student',
        ),
        migrations.DeleteModel(
            name='BudgetSemester',
        ),
    ]
