# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0003_auto_20170619_1229'),
        ('bill2myprint', '0003_auto_20170620_0549'),
    ]

    operations = [
    ]
