# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill2myprint', '0005_consolidatedtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatedtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SEMESTER_ALLOWANCE', 'Allocation semestrielle'), ('FACULTY_ALLOWANCE', 'Rallonge facultaire'), ('ACCOUNT_CHARGING', "Chargement par l'étudiant"), ('TOTAL_SPENT', 'Total dépensé en impressions')], db_index=True, max_length=100),
        ),
    ]
