# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.CharField(default='nike', max_length=255),
            preserve_default=False,
        ),
    ]
