# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAllTransactions',
            fields=[
                ('trans_id', models.IntegerField(db_column='TRANS_ID', primary_key=True, serialize=False)),
                ('trans_origin', models.CharField(db_column='TRANS_ORIGIN', max_length=20)),
                ('trans_amount', models.FloatField(db_column='TRANS_AMOUNT')),
                ('trans_description', models.CharField(blank=True, db_column='TRANS_DESCRIPTION', max_length=94, null=True)),
                ('trans_source', models.CharField(blank=True, db_column='TRANS_SOURCE', max_length=50, null=True)),
                ('person_sciper', models.CharField(blank=True, db_column='PERSON_SCIPER', max_length=10, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trans_datetime', models.DateTimeField(db_column='TRANS_DATETIME')),
                ('trxdateonly', models.DateTimeField(blank=True, null=True)),
                ('trxyear', models.IntegerField(blank=True, null=True)),
                ('trxmonth', models.IntegerField(blank=True, null=True)),
                ('trxweek', models.IntegerField(blank=True, null=True)),
                ('trxday', models.IntegerField(blank=True, null=True)),
                ('trxwday', models.IntegerField(blank=True, null=True)),
                ('trxhourdec', models.FloatField(blank=True, null=True)),
                ('trx_physical_device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trx_docname', models.CharField(blank=True, max_length=300, null=True)),
                ('trx_numcopies', models.IntegerField(blank=True, null=True)),
                ('trx_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_streamsize', models.IntegerField(blank=True, null=True)),
                ('trx_colored', models.IntegerField(blank=True, null=True)),
                ('trx_bw_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_color_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_duplex_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_a6_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_a5_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_a4_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_a3_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_a2_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_a1_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_a0_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_letter_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_legal_page_count', models.IntegerField(blank=True, null=True)),
                ('trx_a6_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_a5_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_a4_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_a3_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_a2_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_a1_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_a0_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_letter_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_legal_sheet_count', models.IntegerField(blank=True, null=True)),
                ('trx_pagesets_summary', models.CharField(blank=True, max_length=4000, null=True)),
                ('user_unit_id', models.IntegerField(blank=True, db_column='USER_UNIT_ID', null=True)),
                ('cf', models.CharField(blank=True, max_length=6, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hierarchie2', models.CharField(blank=True, max_length=300, null=True)),
                ('hierarchie3', models.CharField(blank=True, max_length=300, null=True)),
                ('hierarchie4', models.CharField(blank=True, max_length=300, null=True)),
                ('user_class', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'T_ALL_TRANSACTIONS',
                'managed': False,
            },
        ),
    ]
