# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitrac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSemester',
            fields=[
                ('smst_id', models.AutoField(db_column='SMST_ID', primary_key=True, serialize=False)),
                ('smst_name', models.CharField(db_column='SMST_NAME', max_length=50)),
                ('smst_end_date', models.DateTimeField(db_column='SMST_END_DATE')),
                ('smst_end_date_official', models.DateTimeField(db_column='SMST_END_DATE_OFFICIAL')),
                ('smst_central_allowance_date', models.DateTimeField(blank=True, db_column='SMST_CENTRAL_ALLOWANCE_DATE', null=True)),
            ],
            options={
                'db_table': 'T_SEMESTER',
                'managed': False,
            },
        ),
    ]
