# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitrac', '0002_tsemester'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasTrxAccExt',
            fields=[
                ('x_id', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('operatorworkstation', models.CharField(max_length=255)),
                ('operatorname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cas_trx_acc_ext',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTransaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trxtype', models.CharField(max_length=3)),
                ('trxsubtype', models.CharField(blank=True, max_length=3, null=True)),
                ('devid', models.IntegerField(blank=True, null=True)),
                ('subdeviceid', models.IntegerField(blank=True, null=True)),
                ('chargeid', models.IntegerField(blank=True, null=True)),
                ('accountid', models.IntegerField(blank=True, null=True)),
                ('ct1accountid', models.IntegerField(blank=True, null=True)),
                ('ct2accountid', models.IntegerField(blank=True, null=True)),
                ('trxdate', models.DateTimeField()),
                ('creation', models.DateTimeField()),
                ('lastmodified', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('internalamount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('chargeaccbalance', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('plid', models.IntegerField(blank=True, null=True)),
                ('internalplid', models.IntegerField(blank=True, null=True)),
                ('refid', models.IntegerField(blank=True, null=True)),
                ('valexception', models.TextField(blank=True, null=True)),
                ('trxstate', models.SmallIntegerField()),
                ('applicationname', models.CharField(blank=True, max_length=255, null=True)),
                ('trxguid', models.CharField(max_length=64, unique=True)),
                ('approvedbyid', models.IntegerField(blank=True, null=True)),
                ('freemoneybalance', models.DecimalField(decimal_places=5, max_digits=20)),
                ('freemoneyamount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('grouptrxguid', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'cat_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatValidation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valtype', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('pid', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=5, max_digits=20)),
                ('hardlimit', models.DecimalField(decimal_places=5, max_digits=20)),
                ('creation', models.DateTimeField()),
                ('lastmodified', models.DateTimeField()),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('state', models.SmallIntegerField()),
                ('primarypin', models.CharField(blank=True, max_length=255, null=True)),
                ('secondarypin', models.CharField(blank=True, max_length=255, null=True)),
                ('parid', models.IntegerField()),
                ('locationid', models.IntegerField(blank=True, null=True)),
                ('nonbillable', models.SmallIntegerField(blank=True, null=True)),
                ('freemoney', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
            options={
                'db_table': 'cat_validation',
                'managed': False,
            },
        ),
    ]
